name: barker_tour
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  card_slider: ^1.0.5
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.3
  flutter_phosphor_icons: ^0.0.1+6
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  go_router: ^14.2.3
  logger: ^2.4.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  soft_edge_blur: ^0.1.3
  uuid: ^4.5.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/videos/
    - assets/videos/splash.mp4
    - assets/fonts/
